### ISSUE TITLE
ERROR: Could not open requirements file

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#10]
`pip3 install -r requirements.txt` gives me `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by capital-G** [comment]
@telephon you have to execute the file in the root directory of this repo - there is a `requirements.txt`

**Comment by telephon** [comment]
```
$ ls
bin		lib		pyvenv.cfg
```

**Comment by capital-G** [comment]
@telephon how it is intended (currently writing on this)

```shell
git clone https://github.com/capital-G/musikinformatik-sose2021.git
cd musikinformatik-sose-2021
# now create a new virtual env in the current dir
virtualenv venv
# activate the venv which relinks the environment variables from /usr/bin/python3 to ~/mycode/musikinformatik.../venv/bin/python3
source venv/bin/activate
# install dependencies - still same dir
pip3 install -r requirements.tx
```

**Comment by telephon** [comment]
`requirements.txt`

ja, das geht natürlich!

Von `git clone https://github.com/capital-G/musikinformatik-sose2021.git` war bisher ja garnicht die Rede … :)
