### ISSUE TITLE
note_seq ModuleNotFoundError

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#42]
On `import note_seq` I suddenly get an error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-7a314a24223e> in <module>
----> 1 import note_seq

ModuleNotFoundError: No module named 'note_seq'
```

**Comment by telephon** [comment]
OK, we should add to the documentation that one has to repeat the call of `pip3 install -r requirements.txt` under certain circumstances. I leave the issue open, it is a documentation issue only.

**Comment by capital-G** [comment]
Are you sure you have activated the virtual environment?

Can activate the environment in a shell and post the result of the commands

```shell
which pip3
```
and
```shell
pip3 freeze
```

Could you also post the results of 

```python
import sys
print(sys.path)
```
when executed in a notebook?

**Comment by capital-G** [comment]
Glad to hear that you found a fix

> OK, we should add to the documentation that one has to repeat the call of `pip3 install -r requirements.txt` under certain circumstances. I leave the issue open, it is a documentation issue only.

It is actually already advised in the docs, see the last part of https://capital-g.github.io/musikinformatik-sose2021/docs/course-info/setup.html#updating-the-course-material
Maybe this should be made more clearly?

**Comment by telephon** [comment]
It would be good to know what one has to do to start the python lab when one had it running before.

**Comment by capital-G** [comment]
Do you mean Jupyter Lab?
Have you a suggestion for an improvement on the formulation here? https://capital-g.github.io/musikinformatik-sose2021/docs/course-info/setup.html#start-jupyter-lab

**Comment by capital-G** [comment]
@telephon can we close this or do we need some changes?
