### ISSUE TITLE
minor simplification in plt.scatter 

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#46]
in `01_spect_resynth/02_spect.ipynb`

instead of 
`plt.scatter(x=data_tsne, y=np.zeros(data_tsne.shape), c=list(range(len(data_tsne))))`

can be simplified to
`plt.scatter(x=data_tsne, y=np.zeros(len(data_tsne)), c=range(len(data_tsne)))`

(and in all the other examples)

**Comment by capital-G** [comment]
did not know that plt also accepts an iterator in this case.

Maybe an even better way would be

```python
plt.scatter(x=data_tsne, y=np.zeros(len(data_tsne)), c=np.arange(len(data_tsne)))
```
